version: '3.9'

networks:
  internal_net:
    external: true

services:
  gitea:
    image: gitea/gitea:1.21.11
    container_name: gitea
    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: postgres:5432
      GITEA__database__NAME: gitea_db
      GITEA__database__USER: gitea_user
      GITEA__database__PASSWD: StrongGiteaPass123
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "3000:3000"   # واجهة الويب
      - "222:22"      # SSH Git
    networks:
      - internal_net

