version: '3.9'

networks:
  internal_net:
    external: true

services:
  gitea:
    image: gitea/gitea:1.24.3
    container_name: gitea
    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: postgres_server
      GITEA__database__NAME: gitea_db
      GITEA__database__USER: gitea_user
      GITEA__database__PASSWD: pass
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "7200:3000"   # webui
      - "222:22"      # SSH Git
    networks:
      - internal_net

