# version: "3"
# services:
#   syncthing:
#     image: lscr.io/linuxserver/syncthing:latest
#     container_name: Syncthing
#     hostname: syncthing #optional
#     environment:
#       - PUID=1000
#       - PGID=1000
#       - TZ=$TZ
#     volumes:
#       - $CONFIG:/config
#       - $DATA:$DATA2
#     ports:
#       - 8384:8384
#       - 22000:22000/tcp
#       - 22000:22000/udp
#       - 21027:21027/udp
#     restart: unless-stopped
# #     networks:
# #       - galaxy

# # networks:
# #   galaxy:  # Updated to correct network name
# #     driver: bridge