version: "3.9"

networks:
  db_stack_internal_net:
    external: true

services:
  redis:
    image: redis:7-alpine
    container_name: hs_redis
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    networks: [db_stack_internal_net]

  hyperswitch:
    image: ghcr.io/juspay/hyperswitch:latest
    container_name: hyperswitch
    depends_on:
      - redis
    environment:
      # Postgres الموجود عندك في ستاك db_stack اسمه postgres_db على نفس الشبكة
      DATABASE_URL: "postgres://hyperswitch:CHANGE_ME_STRONG@postgres_db:5432/hyperswitch_db"
      # إعدادات Redis
      REDIS_HOST: "hs_redis"
      REDIS_PORT: "6379"
      # لوجات
      RUST_LOG: "info"
    ports:
      - "8088:8080"   # واجهة الـ router (الصورة الافتراضية بتسمع على 8080)
    restart: unless-stopped
    networks: [db_stack_internal_net]

