version: '3.8'
services:
  influxdb:
    image: influxdb
    container_name: Monitor-InfluxDB
    ports:
      - 8086:8086
    volumes:
      - /home/mrp/docker/monitoring/influxdb/data:/var/lib/influxdb2
      - /home/mrp/docker/monitoring/influxdb/config:/etc/influxdb2
    restart: always
