version: "3.9"

networks:
  db_stack_internal_net:
    external: true   # نفس الشبكة اللي فيها mariadb_db

services:
  babybuddy:
    image: lscr.io/linuxserver/babybuddy:latest
    container_name: babybuddy
    environment:
      - PUID=1000                 # عدّلهم لقيم user/group عندك
      - PGID=1000
      - TZ=Africa/Cairo
      # إعدادات قاعدة البيانات طبقًا لتوثيق Baby Buddy:
      - DB_ENGINE=django.db.backends.mysql
      - DB_HOST=mariadb_db
      - DB_PORT=3306
      - DB_NAME=babybuddy_db      # أنشئها أو خلّي الصورة تنشئ الجداول بداخلها
      - DB_USER=momaher           # لو حابب خصّص يوزر مختلف، غيّره هنا وفي MariaDB
      - DB_PASSWORD=Mohamed@9498#
    volumes:
      - /home/mrmo/babybuddy/config:/config
    ports:
      - "8000:8000"               # غيّر البورت لو محجوز
    restart: unless-stopped
    networks:
      - db_stack_internal_net
