version: '3.9'

services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /home/mrmo/nextcloud/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example-root-pass
      MYSQL_PASSWORD: nextcloudpass
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - /home/mrmo/nextcloud/redis:/data

  app:
    image: nextcloud:27-apache
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - 8080:80
    volumes:
      - /home/mrmo/nextcloud/html:/var/www/html
    environment:
      MYSQL_PASSWORD: nextcloudpass
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
      REDIS_HOST: redis
      REDIS_HOST_PORT: 6379
      TRUSTED_PROXIES: 172.0.0.0/8
      OVERWRITEPROTOCOL: https
    networks:
      - nextcloud-net

  cron:
    image: nextcloud:27-apache
    restart: unless-stopped
    volumes:
      - /home/mrmo/nextcloud/html:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      - nextcloud-net

networks:
  nextcloud-net:
    driver: bridge
